// SPDX-License-Identifier: AGPL-3.0-or-later

using Content.Shared.Pinpointer;

namespace Content.Server.Traitor.Meeting;

/// <summary>
/// Restricts traitor meeting hints to a curated set of standard station nav-map beacons.
/// </summary>
public sealed partial class TraitorMeetingSystem
{
    private static readonly HashSet<string> AllowedMeetingBeaconPrototypeIds = new(StringComparer.Ordinal)
    {
        "DefaultStationBeaconCommand",
        "DefaultStationBeaconBridge",
        "DefaultStationBeaconVault",
        "DefaultStationBeaconGateway",
        "DefaultStationBeaconHOPOffice",
        "DefaultStationBeaconSecurity",
        "DefaultStationBeaconBrig",
        "DefaultStationBeaconDetectiveRoom",
        "DefaultStationBeaconCourtroom",
        "DefaultStationBeaconLawOffice",
        "DefaultStationBeaconMedical",
        "DefaultStationBeaconMedbay",
        "DefaultStationBeaconChemistry",
        "DefaultStationBeaconCryonics",
        "DefaultStationBeaconMorgue",
        "DefaultStationBeaconSurgery",
        "DefaultStationBeaconPsychology",
        "DefaultStationBeaconClinic",
        "DefaultStationBeaconParamedic",
        "DefaultStationBeaconScience",
        "DefaultStationBeaconRND",
        "DefaultStationBeaconSupply",
        "DefaultStationBeaconCargoReception",
        "DefaultStationBeaconCargoBay",
        "DefaultStationBeaconEngineering",
        "DefaultStationBeaconGravGen",
        "DefaultStationBeaconAnchor",
        "DefaultStationBeaconSingularity",
        "DefaultStationBeaconPowerBank",
        "DefaultStationBeaconTelecoms",
        "DefaultStationBeaconAtmospherics",
        "DefaultStationBeaconTEG",
        "DefaultStationBeaconTechVault",
        "DefaultStationBeaconShipyard",
        "DefaultStationBeaconSolarsN",
        "DefaultStationBeaconSolarsNE",
        "DefaultStationBeaconSolarsE",
        "DefaultStationBeaconSolarsSE",
        "DefaultStationBeaconSolarsS",
        "DefaultStationBeaconSolarsSW",
        "DefaultStationBeaconSolarsW",
        "DefaultStationBeaconSolarsNW",
        "DefaultStationBeaconService",
        "DefaultStationBeaconKitchen",
        "DefaultStationBeaconBar",
        "DefaultStationBeaconBotany",
        "DefaultStationBeaconJanitorsCloset",
        "DefaultStationBeaconChapel",
        "DefaultStationBeaconLibrary",
        "DefaultStationBeaconReporter",
        "DefaultStationBeaconTheater",
        "DefaultStationBeaconDorms",
        "DefaultStationBeaconToolRoom",
        "DefaultStationBeaconDisposals",
        "DefaultStationBeaconCryosleep",
        "DefaultStationBeaconVox",
        "DefaultStationBeaconAI",
        "DefaultStationBeaconAISatellite",
        "DefaultStationBeaconArrivals",
        "DefaultStationBeaconEvac",
        "DefaultStationBeaconEVAStorage",
        "DefaultStationBeaconEscapePodN",
        "DefaultStationBeaconEscapePodNE",
        "DefaultStationBeaconEscapePodE",
        "DefaultStationBeaconEscapePodSE",
        "DefaultStationBeaconEscapePodS",
        "DefaultStationBeaconEscapePodSW",
        "DefaultStationBeaconEscapePodW",
        "DefaultStationBeaconEscapePodNW",
    };

    private static readonly HashSet<string> AllowedMeetingBeaconDefaultTextIds = new(StringComparer.Ordinal)
    {
        "station-beacon-command",
        "station-beacon-bridge",
        "station-beacon-vault",
        "station-beacon-gateway",
        "station-beacon-hop",
        "station-beacon-security",
        "station-beacon-brig",
        "station-beacon-detective",
        "station-beacon-courtroom",
        "station-beacon-law",
        "station-beacon-medical",
        "station-beacon-medbay",
        "station-beacon-chemistry",
        "station-beacon-cryonics",
        "station-beacon-morgue",
        "station-beacon-surgery",
        "station-beacon-psychology",
        "station-beacon-clinic",
        "station-beacon-paramedic",
        "station-beacon-science",
        "station-beacon-research-and-development",
        "station-beacon-supply",
        "station-beacon-cargo",
        "station-beacon-cargo-bay",
        "station-beacon-engineering",
        "station-beacon-gravgen",
        "station-beacon-anchor",
        "station-beacon-pa",
        "station-beacon-smes",
        "station-beacon-telecoms",
        "station-beacon-atmos",
        "station-beacon-teg",
        "station-beacon-tech-vault",
        "station-beacon-shipyard",
        "station-beacon-solars-N",
        "station-beacon-solars-NE",
        "station-beacon-solars-E",
        "station-beacon-solars-SE",
        "station-beacon-solars-S",
        "station-beacon-solars-SW",
        "station-beacon-solars-W",
        "station-beacon-solars-NW",
        "station-beacon-service",
        "station-beacon-kitchen",
        "station-beacon-bar",
        "station-beacon-botany",
        "station-beacon-janitor",
        "station-beacon-chapel",
        "station-beacon-library",
        "station-beacon-reporter",
        "station-beacon-theater",
        "station-beacon-dorms",
        "station-beacon-tools",
        "station-beacon-disposals",
        "station-beacon-cryosleep",
        "station-beacon-vox",
        "station-beacon-ai",
        "station-beacon-ai-sat",
        "station-beacon-arrivals",
        "station-beacon-evac",
        "station-beacon-eva-storage",
        "station-beacon-escape-pod-N",
        "station-beacon-escape-pod-NE",
        "station-beacon-escape-pod-E",
        "station-beacon-escape-pod-SE",
        "station-beacon-escape-pod-S",
        "station-beacon-escape-pod-SW",
        "station-beacon-escape-pod-W",
        "station-beacon-escape-pod-NW",
    };

    private bool IsAllowedMeetingBeacon(EntityUid uid, NavMapBeaconComponent beacon)
    {
        // The allow-list accepts the stable prototype ID first, then the default localization key.
        // This keeps map-specific child prototypes usable without relying on the displayed language.
        var prototypeId = MetaData(uid).EntityPrototype?.ID;
        if (prototypeId != null && AllowedMeetingBeaconPrototypeIds.Contains(prototypeId))
            return true;

        return beacon.DefaultText != null && AllowedMeetingBeaconDefaultTextIds.Contains(beacon.DefaultText);
    }
}
