// SPDX-License-Identifier: AGPL-3.0-or-later

using Content.Client.UserInterface.Controls;
using Content.Shared._CorvaxGoob.Traitor.HighRiskPinpointer;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._CorvaxGoob.Traitor.HighRiskPinpointer;

/// <summary>
/// Lets the user choose a fixed high-risk target or switch to exact DNA tracking in one compact window.
/// </summary>
[GenerateTypedNameReferences]
public sealed partial class HighRiskPinpointerWindow : FancyWindow
{
    // OptionButton selection methods use list indexes, so this must remain a valid index.
    private const int DnaSelectionId = (int) HighRiskPinpointerTarget.WardenShotgun + 1;

    public event Action<HighRiskPinpointerTarget>? TargetSelected;
    public event Action<string>? DnaSubmitted;
    public event Action<int>? SelectionChanged;

    public HighRiskPinpointerWindow()
    {
        RobustXamlLoader.Load(this);

        AddTarget(HighRiskPinpointerTarget.Hypospray, "high-risk-pinpointer-target-hypospray");
        AddTarget(HighRiskPinpointerTarget.ResearchDirectorHardsuit, "high-risk-pinpointer-target-rd-hardsuit");
        AddTarget(HighRiskPinpointerTarget.HandTeleporter, "high-risk-pinpointer-target-hand-teleporter");
        AddTarget(HighRiskPinpointerTarget.AdvancedMagboots, "high-risk-pinpointer-target-magboots");
        AddTarget(HighRiskPinpointerTarget.QuartermasterClipboard, "high-risk-pinpointer-target-qm-clipboard");
        AddTarget(HighRiskPinpointerTarget.GoldenKnuckledusters, "high-risk-pinpointer-target-knuckledusters");
        AddTarget(HighRiskPinpointerTarget.CorgiMeat, "high-risk-pinpointer-target-corgi-meat");
        AddTarget(HighRiskPinpointerTarget.HeadOfPersonnelCorgi, "high-risk-pinpointer-target-hop-corgi");
        AddTarget(HighRiskPinpointerTarget.CaptainId, "high-risk-pinpointer-target-captain-id");
        AddTarget(HighRiskPinpointerTarget.CaptainJetpack, "high-risk-pinpointer-target-captain-jetpack");
        AddTarget(HighRiskPinpointerTarget.AntiqueLaser, "high-risk-pinpointer-target-antique-laser");
        AddTarget(HighRiskPinpointerTarget.NuclearDisk, "high-risk-pinpointer-target-nuclear-disk");
        AddTarget(HighRiskPinpointerTarget.HeadOfSecurityMagnum, "high-risk-pinpointer-target-hos-magnum");
        AddTarget(HighRiskPinpointerTarget.WardenShotgun, "high-risk-pinpointer-target-warden-shotgun");
        TargetSelector.AddItem(Loc.GetString("high-risk-pinpointer-dna-button"), DnaSelectionId);
        SelectTarget((int) HighRiskPinpointerTarget.Hypospray);

        TargetSelector.OnItemSelected += args =>
        {
            TargetSelector.SelectId(args.Id);
            DnaInput.Visible = args.Id == DnaSelectionId;
            SelectionChanged?.Invoke(args.Id);
        };
        SearchButton.OnPressed += _ => SubmitSearch();
        DnaInput.OnTextEntered += _ => SubmitSearch();
    }

    private void AddTarget(HighRiskPinpointerTarget target, string name)
    {
        var id = (int) target;
        TargetSelector.AddItem(Loc.GetString(name), id);
        TargetSelector.SetItemMetadata(TargetSelector.GetIdx(id), target);
    }

    /// <summary>
    /// Restores the last selection after the pinpointer window is opened again.
    /// </summary>
    public void SelectTarget(int id)
    {
        if (!TargetSelector.TrySelectId(id))
            return;

        DnaInput.Visible = id == DnaSelectionId;
    }

    private void SubmitSearch()
    {
        if (TargetSelector.SelectedId == DnaSelectionId)
        {
            if (!string.IsNullOrWhiteSpace(DnaInput.Text))
                DnaSubmitted?.Invoke(DnaInput.Text);

            return;
        }

        if (TargetSelector.SelectedMetadata is HighRiskPinpointerTarget target)
            TargetSelected?.Invoke(target);
    }
}
