// SPDX-License-Identifier: AGPL-3.0-or-later

using System.Linq;
using System.Numerics;
using Content.Shared.Ghost.Roles;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Timing;

namespace Content.Client.UserInterface.Systems.Ghost.Controls.Roles;

[GenerateTypedNameReferences]
public sealed partial class GhostRolesPriorityPanel : DefaultWindow
{
    private const float PanelWidth = 280f;
    private const float PanelGap = 4f;

    private readonly GhostRolesWindow _rolesWindow;

    public event Action<uint>? OnRoleSelected;

    public GhostRolesPriorityPanel(GhostRolesWindow rolesWindow)
    {
        RobustXamlLoader.Load(this);
        _rolesWindow = rolesWindow;
        CloseButton.Visible = false;
    }

    public void OpenAttached()
    {
        Open();
        SyncWithRolesWindow();
    }

    public void SetEntries(IEnumerable<ImportantGhostRoleGroup> entries)
    {
        PriorityEntries.RemoveAllChildren();

        var sortedEntries = entries
            .OrderBy(entry => GetCategorySortOrder(entry.Category))
            .ThenByDescending(entry => entry.Priority)
            .ThenBy(entry => entry.Name)
            .ToList();

        NoPriorityRolesMessage.Visible = sortedEntries.Count == 0;

        foreach (var categoryGroup in sortedEntries.GroupBy(entry => entry.Category))
        {
            PriorityEntries.AddChild(new Label
            {
                Text = Loc.GetString(
                    GetCategoryLocId(categoryGroup.Key),
                    ("rolesCount", categoryGroup.Sum(entry => entry.RolesCount))),
                StyleClasses = { "LabelKeyText" },
                Margin = new Thickness(0, 4, 0, 2),
            });

            PriorityEntries.AddChild(new PanelContainer
            {
                StyleClasses = { "HighDivider" },
                Margin = new Thickness(0, 0, 0, 4),
            });

            foreach (var entry in categoryGroup)
            {
                var button = new Button
                {
                    Text = Loc.GetString(
                        "ghost-roles-priority-panel-entry",
                        ("name", entry.Name),
                        ("rolesCount", entry.RolesCount)),
                    ToolTip = entry.Name,
                    HorizontalExpand = true,
                    Margin = new Thickness(0, 0, 0, 4),
                };

                button.OnPressed += _ => OnRoleSelected?.Invoke(entry.Identifier);
                PriorityEntries.AddChild(button);
            }
        }
    }

    protected override void FrameUpdate(FrameEventArgs args)
    {
        base.FrameUpdate(args);

        if (!_rolesWindow.IsOpen)
        {
            Close();
            return;
        }

        SyncWithRolesWindow();
    }

    protected override DragMode GetDragModeFor(Vector2 relativeMousePos)
    {
        return DragMode.None;
    }

    private void SyncWithRolesWindow()
    {
        if (Parent is null || !_rolesWindow.IsOpen)
            return;

        var targetSize = new Vector2(PanelWidth, _rolesWindow.Size.Y);
        if (SetSize != targetSize)
            SetSize = targetSize;

        var right = _rolesWindow.Position.X + _rolesWindow.Size.X + PanelGap;
        var left = _rolesWindow.Position.X - PanelWidth - PanelGap;
        float x;

        if (right + PanelWidth <= Parent.Size.X)
        {
            x = right;
        }
        else if (left >= 0f)
        {
            x = left;
        }
        else
        {
            var combinedWidth = _rolesWindow.Size.X + PanelGap + PanelWidth;
            var windowX = Math.Max(0f, (Parent.Size.X - combinedWidth) / 2f);
            LayoutContainer.SetPosition(_rolesWindow, new Vector2(windowX, _rolesWindow.Position.Y));
            x = windowX + _rolesWindow.Size.X + PanelGap;
        }

        var maxY = Math.Max(0f, Parent.Size.Y - targetSize.Y);
        var targetPosition = new Vector2(Math.Clamp(x, 0f, Math.Max(0f, Parent.Size.X - PanelWidth)),
            Math.Clamp(_rolesWindow.Position.Y, 0f, maxY));

        if (Position != targetPosition)
            LayoutContainer.SetPosition(this, targetPosition);
    }

    private static int GetCategorySortOrder(GhostRoleCategory category)
    {
        return category == GhostRoleCategory.Antagonist ? 0 : 1;
    }

    private static string GetCategoryLocId(GhostRoleCategory category)
    {
        return category == GhostRoleCategory.Antagonist
            ? "ghost-roles-priority-panel-category-antagonist"
            : "ghost-roles-priority-panel-category-other";
    }
}

public readonly record struct ImportantGhostRoleGroup(
    uint Identifier,
    string Name,
    int RolesCount,
    GhostRoleCategory Category,
    int Priority);
